#!/bin/sh
# This script reads from a remote named pipe and sends notifications  
# via terminal notifier to your desktop. Obviously, I use this with
# irssi and fnotify but really can be used for notifications with 
# any other named pipe and notifier you want

(ssh $REMOTE_ADDRESS -o PermitLocalCommand=no  \
  ": > .irssi/fnotify ; tail -f .irssi/fnotify " |  \
while read heading message; do                      \
  terminal-notifier -title "${heading}" -message "${message}";      \
done)&
